"""Minimal HTTP client for talking to a running workflow backend.

The backend generated by ``meta_agent`` (``main.py``) exposes:

* ``POST /api/run-step``     → SSE stream of AG-UI events
* ``POST /api/reset-session`` → reset a session's WorkflowEngine
* ``GET  /``                 → health (frontend.html or 404, either means "up")

We use only the standard library (``urllib``) so the MCP server has no extra
dependency. AG-UI event ``type`` values we care about::

    RUN_STARTED | RUN_FINISHED | RUN_ERROR
    STEP_STARTED | STEP_FINISHED
    TEXT_MESSAGE_CONTENT  (delta)
    CUSTOM                (name == "step_card" -> value holds the card)
"""

from __future__ import annotations

import json
import logging
import time
import urllib.error
import urllib.request
from typing import Any, Dict, List, Optional

logger = logging.getLogger("flowx.client")

DEFAULT_RUN_TIMEOUT = 300  # seconds for a single run-step stream


def _url(base_url: str, path: str) -> str:
    return base_url.rstrip("/") + path


def health_check(port: int, timeout: float = 30.0) -> bool:
    """Poll the backend until it responds (any HTTP status counts as healthy)."""
    deadline = time.time() + timeout
    url = f"http://127.0.0.1:{port}/"
    while time.time() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=2) as resp:  # noqa: S310 - localhost
                resp.read()
                return True
        except urllib.error.HTTPError:
            # A structured HTTP error still means the server is up.
            return True
        except (urllib.error.URLError, ConnectionError, OSError):
            time.sleep(0.4)
    return False


def reset_session(base_url: str, session_id: str, timeout: float = 30.0) -> Dict[str, Any]:
    body = json.dumps({"sessionId": session_id}).encode("utf-8")
    req = urllib.request.Request(  # noqa: S310 - localhost
        _url(base_url, "/api/reset-session"),
        data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:  # noqa: S310
            raw = resp.read().decode("utf-8", "replace")
            try:
                return json.loads(raw)
            except json.JSONDecodeError:
                return {"ok": True, "raw": raw}
    except Exception as exc:
        return {"ok": False, "error": str(exc)}


def run_step_sse(
    base_url: str,
    *,
    session_id: str,
    step_id: str,
    input: Any = None,
    file_path: Optional[str] = None,
    timeout: float = DEFAULT_RUN_TIMEOUT,
) -> Dict[str, Any]:
    """POST ``/api/run-step`` and consume the SSE stream, returning parsed results.

    Returns a dict with::

        ok            bool      — whether the run finished without error
        stepId        str       — last step id reported
        isFinal       bool      — whether the last step was a terminal step
        completedSteps [str]    — steps completed in this session
        text          str       — concatenated assistant text deltas
        cards         [dict]    — step_card custom event values (in order)
        steps_started [str]     — step ids that started
        error         str|None  — error message if RUN_ERROR
    """
    payload: Dict[str, Any] = {
        "sessionId": session_id,
        "stepId": step_id,
        "input": input,
    }
    if file_path is not None:
        payload["file_path"] = file_path

    body = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(  # noqa: S310 - localhost
        _url(base_url, "/api/run-step"),
        data=body,
        headers={"Content-Type": "application/json", "Accept": "text/event-stream"},
        method="POST",
    )

    text_parts: List[str] = []
    cards: List[Dict[str, Any]] = []
    steps_started: List[str] = []
    result: Optional[Dict[str, Any]] = None
    error: Optional[str] = None

    with urllib.request.urlopen(req, timeout=timeout) as resp:  # noqa: S310
        for raw_line in resp:
            line = raw_line.decode("utf-8", "replace").rstrip("\r\n")
            if not line.startswith("data:"):
                continue
            data_str = line[len("data:"):].lstrip()
            if not data_str:
                continue
            try:
                event = json.loads(data_str)
            except json.JSONDecodeError:
                logger.debug("non-JSON SSE data skipped: %r", data_str[:200])
                continue

            etype = event.get("type", "")
            if etype == "TEXT_MESSAGE_CONTENT":
                text_parts.append(str(event.get("delta", "")))
            elif etype == "CUSTOM" and event.get("name") == "step_card":
                value = event.get("value", {})
                if isinstance(value, dict):
                    cards.append(value)
            elif etype == "STEP_STARTED":
                steps_started.append(str(event.get("stepName", "")))
            elif etype == "RUN_FINISHED":
                result = event.get("result")
                if not isinstance(result, dict):
                    result = {"raw": result}
            elif etype == "RUN_ERROR":
                error = str(event.get("message", "unknown run error"))

    ok = error is None and (result.get("ok", True) if result else True)
    return {
        "ok": bool(ok),
        "stepId": (result or {}).get("stepId", step_id),
        "isFinal": bool((result or {}).get("isFinal", False)),
        "completedSteps": list((result or {}).get("completedSteps", [])),
        "text": "".join(text_parts),
        "cards": cards,
        "steps_started": [s for s in steps_started if s],
        "error": error,
    }
